-- Historical GPS path tracking per truck
CREATE TABLE IF NOT EXISTS public.truck_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  truck_id BIGINT NOT NULL REFERENCES public.trucks(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_truck_locations_truck_recorded
  ON public.truck_locations (truck_id, recorded_at DESC);

ALTER TABLE public.truck_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view truck location history"
  ON public.truck_locations FOR SELECT
  TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert truck location history"
  ON public.truck_locations FOR INSERT
  TO authenticated WITH CHECK (true);
